### ISSUE TITLE
Use of everypage.sty package that is in legacy status

### ISSUE THREAD

**Issue by calvanese** [dcpurton/pdfoverlay#2]
Hi,
'pdfoverlay' uses the 'everypage' style, which provides functionality that since the Fall 2020 edition of LaTeX has been implemented in LaTeX itself.  'everypage' tries now to deliver its original behaviour, using the new LaTeX functionality, but the emulation is not strictly equivalent.
Indeed, for a pdf document I have been using, 'pdfoverlay' generated a pdf with an initial blank page, and all overlays were off by one page.

A temporary fix is to use 'everypage-1x' instead of 'everypage', since it provides exactly the old behaviour of 'everypage'. But this may break for future releases of LaTeX, according to the maintainer of everypage.sty.

It would be great if you could update pdfoverlay.sty so that it works correctly also for future releases of LaTeX.

Thanks,
Diego

**Comment by dcpurton** [comment]
Thanks! I'll take a look.
