### ISSUE TITLE
Undefined control sequence. \pdfoverlaySetPDF{...}

### ISSUE THREAD

**Issue by xAlien95** [dcpurton/pdfoverlay#3]
Thank you for providing this package. I'm using the latest version (v1.2).

Given the following .tex file, it generates the .pdf correctly, but at the end of the compilation it shows the following errors:

```diff
   1 \documentclass{article}
   2 \usepackage{pdfoverlay}
   3
-  4 \pdfoverlaySetPDF{capitolo1.pdf}
   5
   6 \begin{document}
   7 Annotation on page 1.
   8 \pdfoverlayIncludeToPage{10}
   9 Annotation on page 10.
  10 \pdfoverlayIncludeToLastPage
  11 \end{document}
```

Type | Line | |
| - | - | -
error | line 4 | Undefined control sequence. `\pdfoverlaySetPDF{capitolo1.pdf}`
error | line 4 | Package pdfoverlay Error: DVI mode not supported. `\pdfoverlaySetPDF{capitolo1.pdf}`

Is there anything I can do to suppress that error?

**Comment by dcpurton** [comment]
@xAlien95 , which TeX engine are you using?

**Comment by dcpurton** [comment]
Oh, I see! I'm sure it didn't used to do that!

**Comment by xAlien95** [comment]
> [...] which TeX engine are you using?

It's `pdflatex`:

```
PDFLATEX: pdflatex -version
pdfTeX 3.14159265-2.6-1.40.21 (TeX Live 2020)
kpathsea version 6.3.2
```

**Comment by dcpurton** [comment]
This happens because for some reason `\sys_if_output_pdf:TF` is not defined in the preamble.

For now, you can set the PDF after `\begin{document}`:

```TeX
\documentclass{article}
\usepackage{pdfoverlay}
\begin{document}
\pdfoverlaySetPDF{capitolo1.pdf}
Annotation on page 1.
\pdfoverlayIncludeToPage{10}
Annotation on page 10.
\pdfoverlayIncludeToLastPage
\end{document}
```

I will follow up with the LaTeX3 team and find out what is going on.

**Comment by xAlien95** [comment]
Thank you.

From my point of view, this solves the issue. Feel free to close this issue if you prefer.

**Comment by dcpurton** [comment]
@xAlien95 Apparently the output format can be changed in the preamble, so this macro is defined late.

Another workaround is to explicitly load `expl3` before loading `pdfoverlay`.

I will fix this issue, but am not yet quite sure what the best option is.

**Comment by dcpurton** [comment]
I've sent a new release to CTAN, so it should be available on the mirrors in a couple of days.
