### ISSUE TITLE
Problems when trying to call a particular pdf by variable name

### ISSUE THREAD

**Issue by chedgala** [dcpurton/pdfoverlay#4]
First of all, thank you for this great package. I'm having a problem setting the pdf background using a variable name.

I pretend to do something like this.

```
\newcommand*{\name}{FCNM}
\usepackage{pdfoverlay}
\pdfoverlaySetPDF{\name.pdf}
```
Of course, this must look ridiculous to you, but I'm just a LaTeX user, not a programmer. 

I would really appreciate your help.
PD: Sorry if this is not the right place to write my doubts.

Best!

**Comment by dcpurton** [comment]
Hi @chedgala ,

Not ridiculous, but I haven't built in a way to do this.

The good news is that it's very easy for you to add this yourself by generating a variant macro that expands its argument once (or more times if you need). You could then make a LaTeX macro for your new expanding variant if you needed it (using `\NewDocumentCommand`).

Try this:

```TeX
\documentclass{article}

\newcommand*{\name}{example-image}

\usepackage{pdfoverlay}

\ExplSyntaxOn
\cs_generate_variant:Nn \pdfoverlay_set_pdf:n { o }
\pdfoverlay_set_pdf:o { \name.pdf }
\ExplSyntaxOff

\begin{document}
\null
\end{document}
```

If you needed a macro that expands its argument more than once you can use:

```TeX
\ExplSyntaxOn
\cs_generate_variant:Nn \pdfoverlay_set_pdf:n { x }
\pdfoverlay_set_pdf:x { \name.pdf }
\ExplSyntaxOff
```

And if you needed a LaTeX macro, you can use:

```TeX
\ExplSyntaxOn
\cs_generate_variant:Nn \pdfoverlay_set_pdf:n { o }
\NewDocumentCommand \pdfoverlaySetPDFo { m }
  {
    \pdfoverlay_set_pdf:o { #1 }
  }
\ExplSyntaxOff
\pdfoverlaySetPDFo{\name.pdf}
```

**Comment by chedgala** [comment]
Thank you very much for this. I will try this and let you know.

**Comment by dcpurton** [comment]
Another option if you store the entire filename in `\name` is to use `V` variant function. I think this is slightly more efficient and correct `expl3` than the `o` variant:

```TeX
\documentclass{article}

\newcommand*{\name}{example-image.pdf}

\usepackage{pdfoverlay}

\ExplSyntaxOn
\cs_generate_variant:Nn \pdfoverlay_set_pdf:n { V }
\pdfoverlay_set_pdf:V \name
\ExplSyntaxOff

\begin{document}
\null
\end{document}
```

**Comment by chedgala** [comment]
I used the second method. Much neater. Thank you very much!

**Comment by dcpurton** [comment]
@chedgala , can you please check if the lastest changes to master work for you with your original code and no workarounds?

**Comment by chedgala** [comment]
Hi @dcpurton. Sorry the late response. I'm on "vacation". I'm working in overleaf, so I don't know if it automatically load the last version of your package.

Anyway, I'm trying the following codes with no results.

```
% \newcommand*{\namepdf}{Formato_azul}
% \pdfoverlaySetPDF{\namepdf.pdf}

\newcommand*{\namepdf}{Formato_azul.pdf}
\pdfoverlaySetPDF{\namepdf}
```

No one is working.

**Comment by dcpurton** [comment]
Ah, I haven't released it. You would have to check it out of GitHub. And overleaf only rarely gets updates.

**Comment by dcpurton** [comment]
I think it's likely OK, so I'll do a release to CTAN. Eventually it will get to overleaf, but they usually only update once a year.

You could also upload the new style file to you project directory in overleaf.
